---
- name: Install dotfiles playbook
  hosts: all
  become: false
  gather_facts: true

  vars:
    dotfiles_user: cees
    dotfiles_group: cees
    dotfiles_name: Cees van de Griend
    dotfiles_email: cees.van.de.griend@griend.eu

  roles:
    - griend.dotfiles.backup
    - griend.dotfiles.git
    - griend.dotfiles.hushlogin
    - griend.dotfiles.local
    - griend.dotfiles.nvim
    - griend.dotfiles.rust
    - griend.dotfiles.ssh
    - griend.dotfiles.starship
    - griend.dotfiles.tmux
    - griend.dotfiles.zsh
