---
- name: Install local playbook
  hosts: localhost
  connection: local
  become: false
  gather_facts: true

  roles:
    - fonts
    - git
    - gnome_desktop
    - hushlogin
    - local
    - nvim
    - ssh
    - tmux
    - zsh
