---
- name: Install packages playbook
  hosts: workstation02.griend.dev
  become: true
  gather_facts: true
  
  tasks:
    - name: Install packages task
      ansible.builtin.apt:
        name:
          - ansible
          - gnucash
          - htop
          - lsd
          - npm
          - pipx
          - postgresql-client
          - rsync
        state: present

    - name: Install NPM packages task
      community.general.npm:
        name: pyright
        global: true

