---
#
# Should be moved to homelab
#
- name: Install packages playbook
  hosts: all
  become: true
  gather_facts: true
  
  tasks:
    - name: Install packages task
      ansible.builtin.apt:
        name:
          - npm
          - pipx
          - python3-psutil
        state: present

    - name: Install NPM packages task
      community.general.npm:
        name: pyright
        global: true
