---
- name: Install packages playbook
  hosts: workstation02.griend.dev
  become: true
  gather_facts: true
  
  tasks:
    - name: Install packages task
      ansible.builtin.apt:
        name:
          - ansible
          - gnucash
          - htop
          - python3
          - python3-pdm
          - python3-psutil
          - python3-venv
          - rsync
        state: present

