---
- name: ~/.ssh/
  ansible.builtin.file:
    name: '/home/{{ dotfiles_user }}/.ssh'
    state: directory
    owner: '{{ dotfiles_user }}'
    group: '{{ dotfiles_group }}'
    mode: '0700'

- name: ~/.ssh/master/
  ansible.builtin.file:
    name: '/home/{{ dotfiles_user }}/.ssh/master'
    state: directory
    owner: '{{ dotfiles_user }}'
    group: '{{ dotfiles_group }}'
    mode: '0700'

- name: ~/.ssh/config
  ansible.builtin.template:
    src: config.j2
    dest: '/home/{{ dotfiles_user }}/.ssh/config'
    owner: '{{ dotfiles_user }}'
    group: '{{ dotfiles_group }}'
    mode: '0600'
