---
- name: Install packages
  ansible.builtin.apt:
    name: '{{ ssh_packages }}'
    state: present

- name: ~/.ssh/
  ansible.builtin.file:
    name: '/home/{{ dotfiles_user }}/.ssh'
    state: directory
    owner: '{{ dotfiles_user }}'
    group: '{{ dotfiles_group }}'
    mode: '0700'

- name: ~/.ssh/master/
  ansible.builtin.file:
    name: '/home/{{ dotfiles_user }}/.ssh/master'
    state: directory
    owner: '{{ dotfiles_user }}'
    group: '{{ dotfiles_group }}'
    mode: '0700'

- name: ~/.ssh/authorized_keys
  ansible.builtin.template:
    src: authorized_keys.j2
    dest: '/home/{{ dotfiles_user }}/.ssh/authorized_keys'
    owner: '{{ dotfiles_user }}'
    group: '{{ dotfiles_group }}'
    mode: '0600'

- name: ~/.ssh/config
  ansible.builtin.template:
    src: config.j2
    dest: '/home/{{ dotfiles_user }}/.ssh/config'
    owner: '{{ dotfiles_user }}'
    group: '{{ dotfiles_group }}'
    mode: '0600'
