---
all:
  children:
    pve:
      hosts:
        pve01.griend.dev:
        pve02.griend.dev:
    kvm:
      hosts:
        dns01.griend.dev:
        proxy01.griend.dev:
        media01.griend.dev:
        backup01.griend.dev:
        workstation01.griend.dev:
    workstation:
      hosts:
        workstation01.griend.dev:
        workstation02.griend.dev:
