namespace: griend
name: dotfiles
version: 1.0.0
readme: README.md
authors:
  - Cees van de Griend <cees.van.de.griend@griend.eu>

description: Manage my personal dotfiles with ansible

license:
  - EUPL-1.2

tags: [dotfiles]

dependencies:
  ansible.posix: ">= 1.6.2"
  community.general: ">= 10.0.1"

repository: https://gitlab.com/ceesvandegriend/dotfiles
documentation: https://gitlab.com/ceesvandegriend/dotfiles
homepage: https://gitlab.com/ceesvandegriend/dotfiles
issues: https://gitlab.com/ceesvandegriend/dotfiles/-/issues

build_ignore: []
