---
- name: Create rclone config dir
  ansible.builtin.file:
    name: "/home/{{ dotfiles_user }}/.config/rclone"
    state: directory
    owner: "{{ dotfiles_user }}"
    group: "{{ dotfiles_group }}"
    mode: "0700"
  when: backup_role

- name: Copy rclone.conf
  ansible.builtin.copy:
    src: rclone.conf
    dest: "/home/{{ dotfiles_user }}/.config/rclone/rclone.conf"
    owner: "{{ dotfiles_user }}"
    group: "{{ dotfiles_group }}"
    mode: "0700"
  when: backup_role
