---
- name: ssh ~/.ssh/
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.ssh"
    state: directory
    mode: '0700'

- name: ssh ~/.ssh/master/
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.ssh/master"
    state: directory
    mode: '0700'

- name: ssh ~/.ssh/config
  ansible.builtin.template:
    src: config.j2
    dest: "{{ ansible_user_dir }}/.ssh/config"
    mode: '0600'

- name: ssh ~/.ssh/authorized_keys
  ansible.builtin.template:
    src: authorized_keys.j2
    dest: "{{ ansible_user_dir }}/.ssh/authorized_keys"
    mode: '0600'
