---
- name: ~/.ssh/
  ansible.builtin.file:
    name: '/home/{{ dotfiles_user }}/.ssh'
    state: directory
    owner: '{{ dotfiles_user }}'
    group: '{{ dotfiles_group }}'
    mode: '0700'

- name: ~/.ssh/master/
  ansible.builtin.file:
    name: '/home/{{ dotfiles_user }}/.ssh/master'
    state: directory
    owner: '{{ dotfiles_user }}'
    group: '{{ dotfiles_group }}'
    mode: '0700'

- name: ~/.ssh/config
  ansible.builtin.template:
    src: config.j2
    dest: '/home/{{ dotfiles_user }}/.ssh/config'
    owner: '{{ dotfiles_user }}'
    group: '{{ dotfiles_group }}'
    mode: '0600'
    
- name: Copy private ssh keys
  ansible.builtin.copy:
    src: id_ed25519
    dest: '/home/{{ dotfiles_user }}/.ssh/id_ed25519'
    owner: '{{ dotfiles_user }}'
    group: '{{ dotfiles_group }}'
    mode: '0600'
  when: dotfiles_ssh_keys

- name: Copy public ssh keys
  ansible.builtin.copy:
    src: id_ed25519.pub
    dest: '/home/{{ dotfiles_user }}/.ssh/id_ed25519.pub'
    owner: '{{ dotfiles_user }}'
    group: '{{ dotfiles_group }}'
    mode: '0644'
  when: dotfiles_ssh_keys
