---
- name: ~/.config/
  ansible.builtin.file:
    name: '/home/{{ dotfiles_user }}/.config'
    state: directory
    owner: '{{ dotfiles_user }}'
    group: '{{ dotfiles_group }}'
    mode: '0700'

- name: ~/.config/zsh/
  ansible.builtin.file:
    name: '/home/{{ dotfiles_user }}/.config/zsh'
    state: directory
    owner: '{{ dotfiles_user }}'
    group: '{{ dotfiles_group }}'
    mode: '0700'

- name: ~/.zshenv
  ansible.builtin.copy:
    content: |
      export ZDOTDIR=/home/{{ dotfiles_user }}/.config/zsh/
    dest: '/home/{{ dotfiles_user }}/.zshenv'
    owner: '{{ dotfiles_user }}'
    group: '{{ dotfiles_group }}'
    mode: '0600'

- name: ~/.config/.zlogin
  ansible.builtin.template:
    src: zlogin.j2
    dest: '/home/{{ dotfiles_user }}/.config/zsh/.zlogin'
    owner: '{{ dotfiles_user }}'
    group: '{{ dotfiles_group }}'
    mode: '0600'

- name: ~/.config/.zlogout
  ansible.builtin.template:
    src: zlogout.j2
    dest: '/home/{{ dotfiles_user }}/.config/zsh/.zlogout'
    owner: '{{ dotfiles_user }}'
    group: '{{ dotfiles_group }}'
    mode: '0600'

- name: ~/.config/.zprofile
  ansible.builtin.template:
    src: zprofile.j2
    dest: '/home/{{ dotfiles_user }}/.config/zsh/.zprofile'
    owner: '{{ dotfiles_user }}'
    group: '{{ dotfiles_group }}'
    mode: '0600'

- name: ~/.config/.zshenv
  ansible.builtin.template:
    src: zshenv.j2
    dest: '/home/{{ dotfiles_user }}/.config/zsh/.zshenv'
    owner: '{{ dotfiles_user }}'
    group: '{{ dotfiles_group }}'
    mode: '0600'

- name: ~/.config/.zshrc
  ansible.builtin.template:
    src: zshrc.j2
    dest: '/home/{{ dotfiles_user }}/.config/zsh/.zshrc'
    owner: '{{ dotfiles_user }}'
    group: '{{ dotfiles_group }}'
    mode: '0600'

- name: ~/.config/zsh/
  ansible.builtin.template:
    src: '{{ item }}'
    dest: "/home/{{ dotfiles_user }}/.config/zsh/{{ item | basename | replace('.j2', '') }}"
    owner: '{{ dotfiles_user }}'
    group: '{{ dotfiles_group }}'
    mode: '0600'
  with_fileglob:
    - '{{ role_path }}/templates/[0123456789][0123456789]-*.zsh.j2'

- name: Ensure default shell is /usr/bin/zsh
  ansible.builtin.user:
    name: '{{ dotfiles_user }}'
    shell: /usr/bin/zsh
