---
- name: Install packages
  ansible.builtin.apt:
    name: '{{ git_packages }}'
    state: present

- name: ~/.gitconfig
  ansible.builtin.template:
    src: gitconfig.j2
    dest: '/home/{{ dotfiles_user }}/.gitconfig'
    owner: '{{ dotfiles_user }}'
    group: '{{ dotfiles_group }}'
    mode: '0600'
