#!/bin/bash

set -e

CMD=${1:-push}

HOST=backup01.griend.dev
DEST=/srv/backup/Documents

case ${CMD} in
  pull)
      if [ -d ~/Documenten ]; then
        cd ~/Documenten
      elif [ -d ~/Documents ]; then
        cd ~/Documents
      fi

      /usr/bin/rsync -avhz \
        "${HOST}:${DEST}/*" \
        .
    ;;
    push)
      if [ -d ~/Documenten ]; then
        cd ~/Documenten
      elif [ -d ~/Documents ]; then
        cd ~/Documents
      fi

      /usr/bin/rsync -avhz \
        --delete \
        --exclude '.DS_Store' \
        [0123456789][0123456789][0123456789]_* \
        "${HOST}:${DEST}"
    ;;
    *)
      echo "$0 [push|pull]"
      echo "   push: rsync files to backup01"
      echo "   pull: rsync files from backup01"
      exit -1
    ;;
esac

popd

