#!/bin/bash

# set -ex
set -e

# Search for usb01
blkid | grep -s 'UUID="F6AD-326B"'
FOUND=$?

if [ ${FOUND} -eq 1 ]; then
  echo "Error: Can not find usb stick usb01"
  exit 1
fi

if [ -d "${HOME}/Documenten" ]; then
  SRC="${HOME}/Documenten"
elif [ -d "${HOME}/Documents" ]; then
  SRC="${HOME}/Documents"
fi

rsync -avhz \
  --delete \
  --exclude '.DS_Store' \
  ${SRC}/[0123456789][0123456789][0123456789]_* \
  /media/cees/USB01/Documents/
