---
- name: Remove packages
  ansible.builtin.apt:
    name:
      - rustc
      - cargo
    state: absent

- name: Download installer
  ansible.builtin.get_url:
    url: 'https://sh.rustup.rs'
    dest: '/tmp/rustup-init.sh'
    owner: '{{ dotfiles_user }}'
    group: '{{ dotfiles_group }}'
    mode: '0755'
  notify: Execute installer
