---
- name: Create nvim config directory
  ansible.builtin.file:
    name: '{{ item }}'
    state: directory
    owner: '{{ dotfiles_user }}'
    group: '{{ dotfiles_group }}'
    mode: '0700'
  loop:
    - '/home/{{ dotfiles_user }}/.config'

- name: Copy nvim config
  ansible.builtin.copy:
    src: nvim/
    dest: '/home/{{ dotfiles_user }}/.config/nvim/'
    owner: '{{ dotfiles_user }}'
    group: '{{ dotfiles_group }}'
    directory_mode: '0700'
    mode: '0600'
