---
- name: Install playbook
  hosts: all
  become: false
  gather_facts: true

  roles:
    - backup
    - git
    - hushlogin
    - local
    - nvim
    - ssh
    - tmux
    - workstation
    - zsh
